apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cb4l5xvat-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:a366c274b6a1ff2ed32e2eb830adf942d285d7ae@sha256:c0f4619b6e9f915f238b6c38313a52ad2a077fc970f29a597fe401e67d257bf5
          name: container-image
