apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cb4l5xvat-python
  janus-idp.io/tekton: cb4l5xvat-python
  backstage.io/kubernetes-id: cb4l5xvat-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cb4l5xvat-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
