apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cb4l5xvat-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cb4l5xvat-python 
  name: cb4l5xvat-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cb4l5xvat-python 
